# 2. INSTALACIÓN DE CLICKHOUSE (EL MÚSCULO REPLICADO)
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "logs-cluster"
spec:
  configuration:
    # Conecta automáticamente con el Keeper que creamos arriba
    zookeeper:
      nodes:
        - host: "pro-keeper-0.pro-keeper-headless"
          port: 2181
        - host: "pro-keeper-1.pro-keeper-headless"
          port: 2181
        - host: "pro-keeper-2.pro-keeper-headless"
          port: 2181
    clusters:
      - name: "log-storage"
        layout:
          shardsCount: 1
          replicasCount: 3
  templates:
    podTemplates:
      - name: clickhouse-pod
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: clickhouse
                  topologyKey: "kubernetes.io/hostname"
    volumeClaimTemplates:
      - name: ch-storage
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
