- name: MongoDB con ReplicaSet
  hosts: node01
  become: yes
  tasks:
    - name: Copiar archivo
      ansible.builtin.copy:
        src: /home/toletum/cluster/MongoDB/mongo.yaml
        dest: /root/mongo.yaml
        owner: root
        group: root
        mode: "0644"
      ignore_errors: no
      tags: [copy]

    - name: Etiquetar nodos para mongo
      ansible.builtin.command: "kubectl label nodes {{ item }} app=mongo --overwrite"
      loop:
        - node02
        - node03
        - node04
      tags: [labels]

    - name: Aplicar StatefulSet 1
      ansible.builtin.command: kubectl apply -f /root/mongo.yaml
      tags: [apply]
