apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default
spec:
  serviceName: "mongodb-headless" # Debe coincidir con el nombre del servicio headless
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: init-mongodb
          image: alpine:latest
          command:
            - sh
            - -c
            # Nota: chown es importante para que Mongo tenga permisos
            - "chown -R 999:999 /data/db"
          volumeMounts:
            - name: data
              mountPath: /data/db      
      containers:
      - name: mongodb
        image: mongo:8.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: data
          mountPath: /data/db
  
  # Aquí es donde ocurre la magia del Local Path Provisioner
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path" # Asegúrate que este sea el nombre de tu SC
      resources:
        requests:
          storage: 5Gi
