---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      nodePort: 30017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default
spec:
  serviceName: "mongodb-headless"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # hostNetwork y dnsPolicy eliminados a menos que sean estrictamente necesarios
      initContainers:
        - name: init-mongodb
          image: alpine:latest
          command:
            - sh
            - -c
            # Copiamos el keyfile del secret (solo lectura) al volumen persistente para darle permisos 600
            - "cp /mnt/mongodb-keyfile /data/db/keyfile && chmod 600 /data/db/keyfile && chown -R 999:999 /data/db"
          volumeMounts:
            - name: keyfile-secret # El volumen del secret
              mountPath: /mnt
            - name: data # El volumen persistente
              mountPath: /data/db      
      containers:
      - name: mongodb
        image: mongo:8.0
        args:
          - "--replSet"
          - "rs0"
          - "--bind_ip_all"
          - "--auth"
          - "--keyFile=/data/db/keyfile"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: data
          mountPath: /data/db
        # Los probes se mantienen igual...
      volumes:
        - name: keyfile-secret
          secret:
            secretName: mongo-key # Asegúrate de que este Secret exista
            defaultMode: 0400
  
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi
