---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017      # Puerto interno del servicio
      targetPort: 27017 # Puerto del contenedor
      nodePort: 30017   # Puerto que abrirá en la IP de tus nodos (opcional, si no pones uno, K8s elige uno al azar)
      
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: default
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/hostname: "node02"
      initContainers:
        - name: init-mongodb
          image: alpine:latest
          command:
            - sh
            - -c
            - "rm -rf /data/db/* && chown 999:999 /data/db"
          volumeMounts:
            - name: data
              mountPath: /data/db      
      containers:
      - name: mongodb
        image: mongo:8.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
      - name: data
        hostPath:
          path: "/mnt/mongo-data"
          type: DirectoryOrCreate
