---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-conf
  namespace: apisix
data:
  config.yaml: |
    deployment:
      admin:
        allow_admin:
          - 0.0.0.0/0
        admin_key:
          - name: admin
            key: edd1c9f034335f136f87ad84b625c8f1
            role: admin
      etcd:
        host:
          - "http://etcd-0.etcd.apisix.svc.cluster.local:2379"
          - "http://etcd-1.etcd.apisix.svc.cluster.local:2379"
          - "http://etcd-2.etcd.apisix.svc.cluster.local:2379"
    apisix:
      node_listen: 8080
---
# --- APISIX GATEWAY (hostNetwork 8080) ---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apisix
  namespace: apisix
spec:
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: apisix
          image: apache/apisix:3.14.1-debian
          env:
            - name: APISIX_STANDALONE
              value: "false"
          command:
            [
              "sh",
              "-c",
              "/usr/bin/apisix init && /usr/bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'",
            ]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: apisix-conf # Corregida la indentación aquí
---
# --- ADMIN API NODEPORT ---
apiVersion: v1
kind: Service
metadata:
  name: apisix-admin-nodeport
  namespace: apisix
spec:
  type: NodePort
  selector:
    app: apisix
  ports:
    - name: admin
      port: 9180
      targetPort: 9180
      nodePort: 30180
      protocol: TCP

---
# --- ADMIN API NODEPORT ---
apiVersion: v1
kind: Service
metadata:
  name: apisix-admin-clusterip
  namespace: apisix
spec:
  type: ClusterIP
  selector:
    app: apisix
  ports:
    - name: admin
      port: 9180
      targetPort: 9180
      protocol: TCP
