apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: apisix
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: gcr.io/etcd-development/etcd:v3.5.15
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_NAME
              value: "$(MY_POD_NAME)"
            - name: ETCD_DATA_DIR
              value: "/etcd-data"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:2379"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(MY_POD_NAME).etcd.apisix.svc.cluster.local:2379"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:2380"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(MY_POD_NAME).etcd.apisix.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd-0=http://etcd-0.etcd.apisix.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.apisix.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd.apisix.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-apisix"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: data
              mountPath: /etcd-data
  # ESTA ES LA POSICIÓN CORRECTA (Nivel spec del StatefulSet)
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: apisix
spec:
  clusterIP: None # Imprescindible para el descubrimiento entre nodos
  ports:
    - port: 2379
      name: client
      targetPort: 2379
    - port: 2380
      name: peer
      targetPort: 2380
  selector:
    app: etcd
