apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-gateway
  namespace: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix-gateway
  template:
    metadata:
      labels:
        app: apisix-gateway
    spec:
      serviceAccountName: apisix-ingress-controller
      containers:
        # CONTENEDOR 1: APISIX (El Proxy)
        - name: apisix
          image: apache/apisix:3.9.0-debian
          env:
            - name: APISIX_ETCD_HOST
              value: "http://etcd:2379"
          ports:
            - containerPort: 9080
              name: http
            - containerPort: 9180
              name: admin
          readinessProbe:
            httpGet:
              path: /apisix/admin/services
              port: 9180
              httpHeaders:
                - name: X-API-KEY
                  value: edd1c9f034335f136f87ad84b625c88b

        # CONTENEDOR 2: Ingress Controller (El que traduce CRDs a APISIX)
        - name: apisix-ingress-controller
          image: apache/apisix-ingress-controller:1.8.0
          args:
            - /ingress-apisix/apisix-ingress-controller
            - ingress
            - --config-path=/ingress-apisix/conf/config.yaml
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: controller-config
              mountPath: /ingress-apisix/conf
      volumes:
        - name: controller-config
          configMap:
            name: apisix-controller-conf

---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway-public
  namespace: apisix
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
      name: http
  selector:
    app: apisix-gateway
