apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: apisix
spec:
  serviceName: etcd-headless
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.15
        command:
          - etcd
          - --data-dir=/bitnami/etcd/data
          - --name=etcd-0
          - --listen-client-urls=http://0.0.0.0:2379
          - --advertise-client-urls=http://etcd-headless.apisix.svc.cluster.local:2379
        ports:
        - containerPort: 2379
          name: client
        volumeMounts:
        - name: data
          mountPath: /bitnami/etcd/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: apisix
spec:
  clusterIP: None
  ports:
  - port: 2379
    targetPort: 2379
    name: client
  selector:
    app: etcd
