apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: echo-route
  namespace: apisix
spec:
  http:
    - name: all-paths
      match:
        hosts:
          - "*"
        paths:
          - /*
      backend:
        serviceName: echo-service
        servicePort: 8080
