apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: echo-route
  namespace: apisix
spec:
  http:
  - name: echo
    match:
      hosts:
      - "*"
      paths:
      - /*
    backend:
      service:
        name: echo-service
        port:
          number: 8080
